ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS approval_status TEXT DEFAULT 'draft';
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS approved_by UUID REFERENCES profiles(id);
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;
